sudo: required

language: node_js
node_js:
  - 10
  - 12
  - 13

services:
  - docker

before_install:
  - docker build -t jungomi/binaryen .

script:
  - yarn run build
  - yarn run lint
  - yarn run test-coverage
  - yarn run size

notifications:
  email: false
